### ISSUE TITLE
Package installs in wrong location

### ISSUE THREAD

**Issue by JimBiardCics** [conda-forge/funcsigs-feedstock#6]
Funcsigs 1.0.2 py_2 installs in a folder named site-packages at the environment root level instead of in lib/python-2.7/site-packages.

**Comment by jakirkham** [comment]
What version of `conda` are you using? Also were you using `constructor` by chance?

**Comment by JimBiardCics** [comment]
conda 4.2.11, and I don't believe I was using constructor. I installed tensorflow, which had funcsigs as a dependency.

**Comment by jakirkham** [comment]
So this package is a new style noarch package and requires at least `conda` 4.3 to install correctly. IOW recommendation is to upgrade `conda`.

Now `conda` 4.2 should warn about this and use an older style package. Though it may require a newer patch release to have that behavior and get it to work correctly.

**Comment by JimBiardCics** [comment]
That was it. Thanks!
